### PR TITLE
feat: Add Solid support

### PR DESCRIPTION
**Pull request by flashblaze**
I have added support for [SolidJS](https://www.solidjs.com/) but it is not working completely. For some reason the height on the `iframe` is not being correctly set resulting the content being cut off.

If possible, could you help me resolve this? Once this is done I'll add demo for Solid and modify this prop
from `term="Welcome to @giscus/react component!"` to `term="Welcome to @giscus/solid component!"`

image

### CODE REVIEW

**Comment by laymonage** [comment]
Hey, thank you very much!

I dug into this and it seems Solid passes props that have `undefined` values to the web component instead of skipping them. For example, if the `id` value isn't set, the web component will have `id="undefined"` instead of not having the `id`. The resizing issue arises because when the `host` value is empty, `undefined` gets set to the web component's `this.host` property, so the following check always fails:

https://github.com/giscus/giscus-component/blob/06a19f20402b5716d8397d94526b6158d65077d0/web/src/giscus.ts#L163-L164

and the `message` events containing the resize values end up not getting processed.

I fixed it by removing the `undefined` values before passing it to the web component, and it seems to work. I've amended your commit and force-pushed the fix to your branch, so feel free to continue working on it. Though, in the future, I'd recommend creating a separate branch on your fork, instead of working on the `main` branch directly.

**Comment by flashblaze** [comment]
Thanks for helping me with the fix as well as refactoring the code. I have now modified the term and pushed my branch. I'll add the demo once the package is updated on npm. Let me know if I should do any further modifications apart from the demo.

And yes, you're right I'll create a separate branch moving forward.

**Comment by flashblaze** [comment]
Do I need to do anything else @laymonage?

**Comment by laymonage** [comment]
Hey @flashblaze, it's looking good to me, but for some reason the `categoryId` and `repoId` values are not passed to the web component, so I haven't merged this PR. I haven't found what causes this issue and I'm still investigating.

**Comment by laymonage** [comment]
Thanks @flashblaze! It's [up on NPM](https://www.npmjs.com/package/@giscus/solid), first release is v2.2.6. It seems Solid, like Svelte, always re-renders the web component when the props change though, instead of just changing the attributes. This prevents the live config update (without rerendering) feature from working.

**Comment by flashblaze** [comment]
Oh I wasn't aware of this. So you mean HMR won't work on importing this component and changing props right? And thanks a lot for merging my PR though you had to modify a bunch of stuff as well 😅

**Pull request merged**
